apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    meta.helm.sh/release-name: my-chartmuseum
    meta.helm.sh/release-namespace: chartmuseum
  creationTimestamp: "2022-11-03T10:35:06Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: my-chartmuseum
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chartmuseum
    app.kubernetes.io/version: 0.15.0
    helm.sh/chart: chartmuseum-3.9.1
  name: my-chartmuseum
  namespace: chartmuseum
  resourceVersion: "164946"
  uid: bd05d194-ceff-4311-9892-76e79c863b24
spec:
  rules:
  - host: chartmuseum.172.17.255.1
    http:
      paths:
      - backend:
          service:
            name: my-chartmuseum
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - chartmuseum.172.17.255.1
    secretName: chartmuseum.172.17.255.1
status:
  loadBalancer:
    ingress:
    - ip: 172.17.255.1