apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor 
metadata:
  name: nginx-metrics
  namespace: nginx # namespace where prometheus is running
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx # same as above
  endpoints:
  - interval: 10s # scrape interval
    path: /metrics # path to scrape
    port: mon # named port in target app
  namespaceSelector:
    matchNames:
    -  nginx # namespace where the app is running

