apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor 
metadata:
  name: nginx-metrics
  namespace: nginx # namespace where prometheus is running
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx # same as above
  endpoints:
  - interval: 10s # scrape interval
    path: /basic_status # path to scrape
    port: web # named port in target app
  namespaceSelector:
    matchNames:
    - nginx # namespace where the app is running

