apiVersion: networking.k8s.io/v1
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    cert-manager.io/acme-challenge-type: http01
    metallb.universe.tf/address-pool: my-pool
  hosts:
    - name: chartmuseum.192.168.222.1.owoo.org
      path: /
      tls: true
      tlsSecret: chartmuseum.192.168.222.1.owoo.org
