apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    app: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: "nginx"
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pa3mep/nginx:1.3
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: web
            containerPort: 80
        resources:
          requests:
            cpu: "0.25"
            memory: "512Mi"
          limits:
            cpu: "0.5"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            port: web
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            port: web
            path: /
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: web
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 3
          timeoutSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: "nginx"
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
   - name: web
     port: 80
     protocol: TCP
     targetPort: web
  selector:
   app: nginx