apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    app: nginx
    release: prom

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: "nginx"
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
    prometheus.io/scheme: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pa3mep/nginx:1.3
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: web
            containerPort: 80
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:0.11.0'
        imagePullPolicy: "IfNotPresent"
        args:
          - '-nginx.scrape-uri=http://localhost/basic_status'
        ports:
          - containerPort: 9113

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: "nginx"
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
    prometheus.io/scheme: http
spec:
  type: LoadBalancer
  ports:
   - name: web
     port: 80
     protocol: TCP
     targetPort: web
  selector:
   app: nginx