FROM pa3mep/kubernetes-intro:1.0

# COPY ./passwd /etc
# COPY ./group /etc
# COPY ./httpd.conf /usr/local/apache2/conf
# RUN mkdir /app
# COPY ./homework.html /app

# docker build -t kpa3mep/kubernetes-intro:1.0 .

# docker run -p 8000:80 -dit --name web pa3mep/kubernetes-intro:1.0